name: NeoAdmin
version: '1.0-SNAPSHOT'
main: dev.oter.neoAdmin.NeoAdmin
api-version: '1.21'
authors: [ oter42 ]
description: Генний
website: https://t.me/oter993
commands:
  admin:
    description: Основная команда администрирования
    permission: neoadmin.use
  a:
    description: Чат для персонала
    permission: neoadmin.staffchat
permissions:
  neoadmin.use:
    description: Доступ к меню и режимам
    default: op
  neoadmin.mode:
    description: Возможность включать /admin on
    default: op
  neoadmin.staffchat:
    description: Доступ к админ-чату
    default: op